# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(blank=True, max_length=40)),
                ('precio', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
